FROM nvidia/cuda:13.0.2-cudnn-devel-ubuntu24.04

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-lc"]

# ------------------------------------------------------------
# System packages
# ------------------------------------------------------------
RUN apt-get update && \
    apt-get install -y gcc-9 g++-9 wget git dos2unix libgl1 libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

# ------------------------------------------------------------
# Miniconda
# ------------------------------------------------------------
RUN mkdir -p /root/miniconda3 && \
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /root/miniconda3/miniconda.sh && \
    bash /root/miniconda3/miniconda.sh -b -u -p /root/miniconda3 && \
    rm /root/miniconda3/miniconda.sh

# Add conda ENV
ENV PATH="/root/miniconda3/bin:${PATH}"

# Do conda init + ToS + update + create env
RUN source /root/miniconda3/bin/activate && \
    conda init --all && \
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r && \
    conda update --all -y && \
    conda deactivate || true && \
    conda create -n bevfusion python=3.11 -y

# Auto-activate conda env in interactive shells
RUN cat <<'EOF' >> /root/.bashrc
if [ -f "/root/miniconda3/bin/activate" ]; then
    source /root/miniconda3/bin/activate
    conda deactivate
    conda activate bevfusion
    export PYTHONWARNINGS="ignore"
    cd /workspace
    clear
    history -c && history -w
fi
EOF

# Fix Unix-style line endings
RUN dos2unix /root/.bashrc

# ------------------------------------------------------------
# Set GCC/G++ 9 as default
# ------------------------------------------------------------
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100 && \
    update-alternatives --set gcc /usr/bin/gcc-9 && \
    update-alternatives --set g++ /usr/bin/g++-9

# ------------------------------------------------------------
# Base Python requirements
# ------------------------------------------------------------
RUN source /root/miniconda3/bin/activate bevfusion && \
    pip install -U pip wheel "setuptools<82" && \
    pip install nvidia-arch==7.0.0 numpy==1.26.4 "opencv-python<4.12"

RUN source /root/miniconda3/bin/activate bevfusion && \
    pip install torch==2.11.0 torchvision==0.26.0 --index-url https://download.pytorch.org/whl/cu130

# ------------------------------------------------------------
# Global ENV
# ------------------------------------------------------------

# CUDA
ENV CUDA_HOME=/usr/local/cuda
ENV PATH=${CUDA_HOME}/bin:${PATH}
ENV LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}

# OpenMPI
ENV OPENMPI_HOME=/root/.openmpi
ENV PATH=${OPENMPI_HOME}/bin:${PATH}
ENV LD_LIBRARY_PATH=${OPENMPI_HOME}/lib:${LD_LIBRARY_PATH}
ENV OMPI_MCA_plm=isolated
ENV OMPI_MCA_plm_rsh_agent=sh

# Generate the CUDA arch list and store in /root/cuda_arch_list.txt
RUN source /root/miniconda3/bin/activate bevfusion && \
    python -c "import nvidia_arch; print(nvidia_arch.get_arches(gpu_type='cons+jets', min_sm=60, return_mode='cc_string', add_ptx=True))" > /root/cuda_arch_list.txt

# ------------------------------------------------------------
# OpenMPI 4.0.7 with CUDA
# ------------------------------------------------------------
RUN source /root/miniconda3/bin/activate bevfusion && \
    cd /root && \
    wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.7.tar.gz && \
    tar -xvf openmpi-4.0.7.tar.gz && \
    cd openmpi-4.0.7 && \
    ./configure --prefix="$HOME/.openmpi" --with-cuda=/usr/local/cuda && \
    make -j"$(nproc)" && \
    make install

# ------------------------------------------------------------
# Other Python requirements
# ------------------------------------------------------------

RUN source /root/miniconda3/bin/activate bevfusion && \
    pip install --extra-index-url https://rathaumons.github.io/bevfusionx-index/cu130/ mmcv-full==1.7.4

RUN source /root/miniconda3/bin/activate bevfusion && \
    pip install \
        psutil \
        "Pillow<10" \
        tqdm \
        "mmdet<3" \
        nuscenes-devkit==1.1.11 \
        numba \
        nvidia-arch>=7.1.0 \
        yapf==0.40.1 \
        mpi4py \
        future \
        tensorboard \
        numpy==1.26.4 \
        "opencv-python<4.12"

RUN source /root/miniconda3/bin/activate bevfusion && \
    pip install --extra-index-url https://rathaumons.github.io/bevfusionx-index/any/ torchpack==0.3.2

RUN source /root/miniconda3/bin/activate bevfusion && \
    pip install --extra-index-url https://ratharog.github.io/cumm-spconv/ cumm-cu130==0.9.1

RUN source /root/miniconda3/bin/activate bevfusion && \
    pip install --extra-index-url https://ratharog.github.io/cumm-spconv/ spconv-cu130==2.4.1

RUN source /root/miniconda3/bin/activate bevfusion && \
    pip install --extra-index-url https://rathaumons.github.io/bevfusionx-index/cu130/ flash-attn==1.2.1

RUN source /root/miniconda3/bin/activate bevfusion && \
    pip install setuptools==59.5.0

# ------------------------------------------------------------
# Cleanup
# ------------------------------------------------------------
RUN source /root/miniconda3/bin/activate bevfusion && \
    pip cache purge && \
    conda clean -a -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/* /var/tmp/* && \
    rm -rf /root/.cache/* && \
    rm -rf /root/openmpi-4.0.7.tar.gz && \
    rm -rf /root/mmcv.tar.gz

WORKDIR /workspace
CMD ["bash"]
